module.exports = [
  {
    id: 'digestive-system',
    title: 'Digestive System',
    topic: 'Chapter 4 - The Digestive System',
    grade: 6,
    icon: 'stomach',
    questions: [
      { text: 'What is the main job of the digestive system?', options: { A: 'To pump blood around the body', B: 'To break food down into tiny particles the body can use', C: 'To control breathing', D: 'To filter waste from the blood' }, correct: 'B' },
      { text: 'Where does digestion first begin?', options: { A: 'In the stomach', B: 'In the small intestine', C: 'In the mouth', D: 'In the oesophagus' }, correct: 'C' },
      { text: 'What does saliva do during digestion?', options: { A: 'It stores food until digestion is complete', B: 'It makes food moist and contains juices that start digestion', C: 'It absorbs nutrients into the blood', D: 'It pushes food into the large intestine' }, correct: 'B' },
      { text: 'What is the tube that carries food from the mouth to the stomach?', options: { A: 'Large intestine', B: 'Small intestine', C: 'Oesophagus', D: 'Trachea' }, correct: 'C' },
      { text: 'What happens to food inside the stomach?', options: { A: 'It is chewed into smaller pieces', B: 'It is mixed with digestive juices and turned into a thick liquid', C: 'Nutrients pass into the blood', D: 'Waste is removed from the body' }, correct: 'B' },
      { text: 'Which organ breaks food particles small enough to move into the blood?', options: { A: 'Stomach', B: 'Large intestine', C: 'Oesophagus', D: 'Small intestine' }, correct: 'D' },
      { text: 'What is the main job of the large intestine?', options: { A: 'It digests food with enzymes', B: 'It produces saliva', C: 'It absorbs water and moves undigested food toward the anus', D: 'It carries digested food to the heart' }, correct: 'C' },
      { text: 'Iodine turns blue-black when added to bread. What does this show?', options: { A: 'Bread contains fat', B: 'Bread contains protein', C: 'Bread contains starch', D: 'Bread contains vitamins' }, correct: 'C' },
      { text: 'How does digested food reach all parts of the body?', options: { A: 'Through the oesophagus', B: 'Through the large intestine', C: 'Through the blood', D: 'Through the stomach' }, correct: 'C' },
      { text: 'What is the opening through which solid waste leaves the body?', options: { A: 'Stomach', B: 'Anus', C: 'Oesophagus', D: 'Small intestine' }, correct: 'B' },
      { text: 'Which of these animals has a similar digestive system to humans?', options: { A: 'Insects', B: 'Fish', C: 'Rabbits', D: 'Jellyfish' }, correct: 'C' },
      { text: 'What is the process of breaking down food called?', options: { A: 'Respiration', B: 'Digestion', C: 'Circulation', D: 'Absorption' }, correct: 'B' },
      { text: 'Which organs are the main organs of the digestive system?', options: { A: 'Heart and lungs', B: 'Brain and kidneys', C: 'Stomach and small intestine', D: 'Liver and pancreas' }, correct: 'C' },
      { text: 'Is it TRUE or FALSE that digestion starts in the stomach?', options: { A: 'True - digestion begins in the stomach', B: 'False - digestion begins in the mouth', C: 'True - the stomach produces saliva', D: 'False - digestion begins in the intestine' }, correct: 'B' },
      { text: 'Is it TRUE or FALSE that the oesophagus uses muscle contractions to push food down?', options: { A: 'False - gravity does all the work', B: 'False - only liquids travel down the oesophagus', C: 'True - muscles squeeze and push food toward the stomach', D: 'True - but only for solid food' }, correct: 'C' },
      { text: 'Is it TRUE or FALSE that the small intestine absorbs water back into the blood?', options: { A: 'True - it absorbs both water and nutrients', B: 'False - the small intestine only breaks down food', C: 'False - only the large intestine absorbs water', D: 'True - but it absorbs water before nutrients' }, correct: 'C' },
      { text: 'Which part of the digestive system produces saliva?', options: { A: 'The stomach', B: 'The mouth', C: 'The small intestine', D: 'The large intestine' }, correct: 'B' },
      { text: 'What does the small intestine do with food particles?', options: { A: 'Chews them into smaller pieces', B: 'Stores them until the body needs energy', C: 'Breaks them down until they can pass into the blood', D: 'Pushes them out of the body as waste' }, correct: 'C' },
    ]
  },
  {
    id: 'balanced-diet',
    title: 'Balanced Diet',
    topic: 'Chapter 4 - Balanced Diets',
    grade: 6,
    icon: 'apple',
    questions: [
      { text: 'Which food group gives our bodies energy?', options: { A: 'Proteins', B: 'Fats', C: 'Carbohydrates', D: 'Vitamins' }, correct: 'C' },
      { text: 'Which food group helps build our bodies and makes us grow?', options: { A: 'Carbohydrates', B: 'Proteins', C: 'Vitamins', D: 'Minerals' }, correct: 'B' },
      { text: 'Which mineral makes our bones and teeth strong?', options: { A: 'Iron', B: 'Sodium', C: 'Calcium', D: 'Fibre' }, correct: 'C' },
      { text: 'Why do we need fibre in our diet?', options: { A: 'It gives us lots of energy', B: 'It builds muscles', C: 'It helps food move easily through the digestive system', D: 'It repairs damaged cells' }, correct: 'C' },
      { text: 'What does a balanced diet mean?', options: { A: 'Eating only healthy foods', B: 'Eating the right kinds and right amounts from all food groups', C: 'Eating as much protein as possible', D: 'Never eating fats or sugars' }, correct: 'B' },
      { text: 'Why is sugar described as a bad carbohydrate?', options: { A: 'It gives no energy at all', B: 'It is not a carbohydrate', C: 'Too much is unhealthy for the body', D: 'It contains too much fibre' }, correct: 'C' },
      { text: 'Which food group stores energy but can be harmful in large amounts?', options: { A: 'Proteins', B: 'Carbohydrates', C: 'Vitamins', D: 'Fats' }, correct: 'D' },
      { text: 'What is iron needed for in the body?', options: { A: 'To make healthy blood', B: 'To strengthen bones', C: 'To produce energy', D: 'To digest fat' }, correct: 'A' },
      { text: 'Which foods are the best sources of vitamins and minerals?', options: { A: 'Cakes and biscuits', B: 'White bread and white rice', C: 'Fresh fruits, vegetables and fish', D: 'Cola drinks and sweets' }, correct: 'C' },
      { text: 'Why does the body need water?', options: { A: 'Only to cool down during exercise', B: 'To carry substances around the body and help digestion', C: 'To provide vitamins', D: 'It does not - juice is enough' }, correct: 'B' },
      { text: 'Where does fibre come from?', options: { A: 'Animal products like meat and fish', B: 'Plants such as vegetables, fruits and whole grains', C: 'Dairy products like milk and cheese', D: 'Sugary drinks and sweets' }, correct: 'B' },
      { text: 'Is it TRUE or FALSE that we get energy from carbohydrates?', options: { A: 'False - only proteins give energy', B: 'False - fats are the only energy source', C: 'True - carbohydrates are the body\'s main energy source', D: 'True - but only complex carbohydrates give energy' }, correct: 'C' },
      { text: 'Is it TRUE or FALSE that fruits and vegetables contain lots of vitamins and minerals?', options: { A: 'False - vitamins are only in meat', B: 'True - fresh fruits and vegetables are excellent sources', C: 'False - minerals come only from water', D: 'True - but only cooked vegetables count' }, correct: 'B' },
      { text: 'Is it TRUE or FALSE that eating fat is always bad for you?', options: { A: 'True - all fat is harmful', B: 'False - the body needs some fat to store energy', C: 'True - fat causes all diseases', D: 'False - you should eat as much fat as possible' }, correct: 'B' },
      { text: 'Which treatment cured scurvy in James Lind\'s investigation?', options: { A: 'Seawater', B: 'Vinegar', C: 'Garlic and mustard', D: 'Oranges and lemons' }, correct: 'D' },
      { text: 'What substance in fruits and vegetables prevents and cures scurvy?', options: { A: 'Vitamin A', B: 'Vitamin B', C: 'Vitamin C', D: 'Vitamin D' }, correct: 'C' },
    ]
  },
  {
    id: 'forces-magnetism',
    title: 'Forces & Magnetism',
    topic: 'Chapter 5 - Forces and Magnetism',
    grade: 6,
    icon: 'magnet',
    questions: [
      { text: 'What is gravity?', options: { A: 'A force that pushes objects away from Earth', B: 'The force that attracts all objects towards Earth', C: 'A force only felt by moving objects', D: 'A force caused by magnets' }, correct: 'B' },
      { text: 'What is a normal force?', options: { A: 'The force of gravity pulling an object down', B: 'A force that causes objects to roll', C: 'A support force that stops two objects passing through each other', D: 'The force a magnet exerts on metal' }, correct: 'C' },
      { text: 'When equal forces act in opposite directions on an object, what happens?', options: { A: 'The object accelerates upwards', B: 'The object accelerates downwards', C: 'The object remains at rest - the forces are balanced', D: 'The object spins in a circle' }, correct: 'C' },
      { text: 'Which of these is an example of an applied force?', options: { A: 'Gravity pulling a book downwards', B: 'A table supporting a book', C: 'A student pushing a table', D: 'An object remaining still' }, correct: 'C' },
      { text: 'In a force diagram, what does each arrow represent?', options: { A: 'The speed of the object', B: 'The weight of the object', C: 'A force - its direction and size', D: 'The distance the object has moved' }, correct: 'C' },
      { text: 'A book rests on a table. Which two forces act on it?', options: { A: 'Gravity and friction', B: 'Gravity and normal force', C: 'Normal force and applied force', D: 'Gravity and magnetism' }, correct: 'B' },
      { text: 'Is it TRUE or FALSE that gravity only acts on objects that are moving?', options: { A: 'True - stationary objects have no gravity', B: 'False - gravity acts on both moving and stationary objects', C: 'True - only falling objects feel gravity', D: 'False - gravity does not exist on Earth' }, correct: 'B' },
      { text: 'Is it TRUE or FALSE that an applied force happens when an object is pushed or pulled by another?', options: { A: 'False - applied forces only come from machines', B: 'True - any push or pull on an object from another object or person', C: 'False - applied force is the same as gravity', D: 'True - but only if the object moves' }, correct: 'B' },
      { text: 'What happens if you kick a ball? What type of force is this?', options: { A: 'Normal force - the ground supports the ball', B: 'Gravity - the Earth pulls the ball', C: 'Applied force - your foot pushes the ball', D: 'Magnetic force - the foot attracts the ball' }, correct: 'C' },
      { text: 'Why do you NOT sink into the ground when you stand still?', options: { A: 'Because you are too light for gravity to act on you', B: 'Because the normal force from the ground pushes you up equally', C: 'Because gravity does not act when you are still', D: 'Because your shoes protect you' }, correct: 'B' },
      { text: 'What would happen without gravity on Earth?', options: { A: 'Everything would be heavier', B: 'Objects and people would float off the Earth', C: 'Everything would move faster', D: 'Nothing would change' }, correct: 'B' },
      { text: 'Pulling open a door is an example of which type of force?', options: { A: 'Normal force', B: 'Gravity', C: 'Applied pull force', D: 'Magnetic force' }, correct: 'C' },
      { text: 'In a force diagram showing a book on a table, which direction does the gravity arrow point?', options: { A: 'Upwards', B: 'To the right', C: 'Downwards', D: 'In a circle' }, correct: 'C' },
      { text: 'Is it TRUE or FALSE that forces always act in pairs?', options: { A: 'False - some forces act alone', B: 'True - for every force there is an equal and opposite force', C: 'False - only applied forces have pairs', D: 'True - but only gravitational forces are paired' }, correct: 'B' },
      { text: 'When are the arrows in a force diagram the same size?', options: { A: 'When the object is moving fast', B: 'When the forces are equal in size', C: 'When the object is very heavy', D: 'When the object is in water' }, correct: 'B' },
    ]
  }
];
